version: '3.8'

services:
  web:
    container_name: przychodnia-web
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/przychodnia
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
      BETTER_AUTH_URL: ${BETTER_AUTH_URL}
      NUXT_NODEMAILER_FROM: ${NUXT_NODEMAILER_FROM}
      NUXT_NODEMAILER_HOST: ${NUXT_NODEMAILER_HOST}
      NUXT_NODEMAILER_PORT: ${NUXT_NODEMAILER_PORT}
      NUXT_NODEMAILER_SECURE: ${NUXT_NODEMAILER_SECURE}
      NUXT_TURNSTILE_SECRET_KEY: ${NUXT_TURNSTILE_SECRET_KEY}
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'sh', '-c', 'curl -f http://localhost:3000 || exit 1']
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s

  db:
    container_name: przychodnia-db
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: przychodnia
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: '--encoding=UTF8 --locale=C'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d przychodnia']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:
